[package]
name = "twa-axum"
version = "1.1.2"
edition = "2021"
publish = false
license = "Apache-2.0"

[dependencies]
twa-jwks = { path = "../../twa-jwks", version = "1.1.2", features = ["axum"] }
axum = { version = "0.6.20", features = ["macros"] }
tokio = { version = "1.31.0", features = ["full"] }
serde = { version = "1.0.183", features = ["derive"] }
serde_json = { version = "1.0.104" }
