[package]
name = "twa-actix-web"
version = "1.1.5"
edition = "2021"
publish = false
license = "Apache-2.0"

[dependencies]
twa-jwks = { path = "../../twa-jwks", version = "1.1.5", features = ["actix-web"] }
actix-web = { version = "4.3.1", features = ["macros"] }
serde = { version = "1.0.183", features = ["derive"] }
serde_json = { version = "1.0.104" }
