[package]
name = "twa-actix-web"
version = "1.2.5"
edition = "2021"
publish = false
license = "Apache-2.0"

[dependencies]
twa-jwks = { path = "../../twa-jwks", version = "1.2.5", features = ["actix-web"] }
actix-web = { version = "4.4.0", features = ["macros"] }
serde = { version = "1.0.192", features = ["derive"] }
