[package]
name = "twa-jwks"
version = "1.2.10"
edition = "2021"
license = "Apache-2.0"
publish = true
description = "Library to validate JWT tokens using JSON Web Key Set (JWKS)"
repository = "https://github.com/timayz/twa-jwks"
homepage = "https://docs.rs/twa-jwks"
documentation = "https://docs.rs/twa-jwks"
keywords = ["actix-web", "axum", "jwks"]

[dependencies]
actix-web = { version = "4.4.1", optional = true }
axum = { version = "0.7.3", optional = true }
futures-util = { version = "0.3.30", optional = true }
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
thiserror = "1.0.56"
tracing = "0.1.40"
base64 = "0.21.5"
ureq = { version = "2.9.1", features = ["json"] }
regex = "1.10.2"
ring = "0.17.7"
tokio = { version = "1.35.1", features = ["sync"] }

[dev-dependencies]
tokio = { version = "1.35.1", features = ["macros", "rt-multi-thread"] }
tokio-test = "0.4.3"

[features]
default = []
actix-web = ["dep:actix-web", "dep:futures-util"]
axum = ["dep:axum"]
