[package]
name = "twa-jwks"
version = "1.1.5"
edition = "2021"
license = "Apache-2.0"
publish = true
description = "Library to validate JWT tokens using JSON Web Key Set (JWKS)"
repository = "https://github.com/timayz/twa-jwks"
homepage = "https://docs.rs/twa-jwks"
documentation = "https://docs.rs/twa-jwks"
keywords = ["actix-web", "axum", "jwks"]

[dependencies]
actix-web = { version = "4.3.1", optional = true }
axum = { version = "0.6.20", optional = true }
futures-util = { version = "0.3.28", optional = true }
serde = { version = "1.0.183", features = ["derive"] }
serde_json = "1.0.104"
thiserror = "1.0.46"
tracing = "0.1.37"
base64 = "0.21.2"
ureq = { version = "2.7.1", features = ["json"] }
regex = "1.9.3"
ring = "0.16.20"
tokio = { version = "1.31.0", features = ["sync"] }

[dev-dependencies]
tokio = { version = "1.31.0", features = ["macros", "rt-multi-thread"] }
tokio-test = "0.4.2"

[features]
default = []
actix-web = ["dep:actix-web", "dep:futures-util"]
axum = ["dep:axum"]
