[package]
name = "twa-jwks"
version = "1.2.4"
edition = "2021"
license = "Apache-2.0"
publish = true
description = "Library to validate JWT tokens using JSON Web Key Set (JWKS)"
repository = "https://github.com/timayz/twa-jwks"
homepage = "https://docs.rs/twa-jwks"
documentation = "https://docs.rs/twa-jwks"
keywords = ["actix-web", "axum", "jwks"]

[dependencies]
actix-web = { version = "4.4.0", optional = true }
axum = { version = "0.6.20", optional = true }
futures-util = { version = "0.3.29", optional = true }
serde = { version = "1.0.192", features = ["derive"] }
serde_json = "1.0.108"
thiserror = "1.0.50"
tracing = "0.1.40"
base64 = "0.21.5"
ureq = { version = "2.8.0", features = ["json"] }
regex = "1.10.2"
ring = "0.17.5"
tokio = { version = "1.34.0", features = ["sync"] }

[dev-dependencies]
tokio = { version = "1.34.0", features = ["macros", "rt-multi-thread"] }
tokio-test = "0.4.3"

[features]
default = []
actix-web = ["dep:actix-web", "dep:futures-util"]
axum = ["dep:axum"]
