[package]
name = "twa-jwks"
version = "1.2.2"
edition = "2021"
license = "Apache-2.0"
publish = true
description = "Library to validate JWT tokens using JSON Web Key Set (JWKS)"
repository = "https://github.com/timayz/twa-jwks"
homepage = "https://docs.rs/twa-jwks"
documentation = "https://docs.rs/twa-jwks"
keywords = ["actix-web", "axum", "jwks"]

[dependencies]
actix-web = { version = "4.4.0", optional = true }
axum = { version = "0.6.20", optional = true }
futures-util = { version = "0.3.28", optional = true }
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
thiserror = "1.0.49"
tracing = "0.1.37"
base64 = "0.21.4"
ureq = { version = "2.8.0", features = ["json"] }
regex = "1.9.6"
ring = "0.17.2"
tokio = { version = "1.32.0", features = ["sync"] }

[dev-dependencies]
tokio = { version = "1.32.0", features = ["macros", "rt-multi-thread"] }
tokio-test = "0.4.3"

[features]
default = []
actix-web = ["dep:actix-web", "dep:futures-util"]
axum = ["dep:axum"]
